force-app/meta-trigger/default/objects/Trigger_Control__mdt/Trigger_Control__mdt.object-meta.xml
<CustomObject>
    <description>Controls execution of all triggers</description>
    <label>Trigger Control</label>
    <pluralLabel>Trigger Controls</pluralLabel>
</CustomObject>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Which Apex class this service call resides in.</description>
    <inlineHelpText>Which Apex class this service call resides in.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>The name of your method that begins the service call.</description>
    <inlineHelpText>The name of your method that begins the service call.</inlineHelpText>
    <label>Method Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/meta-trigger/default/classes/MetaTriggerManager.cls
/**
 * Created by henryzhao on 2020-01-17.
 */

public class MetaTriggerManager {
    class MetaTriggerManagerException extends Exception {
    }

    private List<Trigger_Control__mdt> activeTriggerControls = new List<Trigger_Control__mdt>();
    private SObjectType objectFiringOn;
    private TriggerOperation dmlOperation;

    public MetaTriggerManager() {
        this.objectFiringOn = Trigger.isDelete ? Trigger.old.getSObjectType() : Trigger.new.getSObjectType();
        this.dmlOperation = Trigger.operationType;
        this.activeTriggerControls = MetaTriggerSelector.retrieveTriggerControls(this.objectFiringOn, this.dmlOperation);
    }

    public void start() {
        for (Trigger_Control__mdt tc : this.activeTriggerControls) {
            Callable dynamicClass = (Callable) Type.forName(tc.Apex_Class__c).newInstance();
            Object old, escapeNew;
            if (Trigger.oldMap == null) {
                old = Trigger.old;
            } else {
                old = Trigger.oldMap;
            }
            if (Trigger.newMap == null) {
                escapeNew = Trigger.new;
            } else {
                escapeNew = Trigger.newMap;
            }
            dynamicClass.call(tc.Method_Name__c, new Map<String, Object>{
                    'old' => old,
                    'new' => escapeNew
            });
        }
        System.debug(LoggingLevel.INFO, '##### MetaTriggerManager -> start -> before -> ' + Trigger.oldMap);
        System.debug(LoggingLevel.INFO, '##### MetaTriggerManager -> start -> after -> ' + Trigger.newMap);
        System.debug(LoggingLevel.INFO, '##### MetaTriggerManager -> start -> objectFiringOn -> ' + objectFiringOn);
        System.debug(LoggingLevel.INFO, '##### MetaTriggerManager -> start -> dmlOperation -> ' + dmlOperation);
        System.debug(LoggingLevel.INFO, '##### MetaTriggerManager -> start -> activeTriggerControls -> ' + activeTriggerControls);
    }

}