force-app/meta-trigger/default/objects/Trigger_Control__mdt/Trigger_Control__mdt.object-meta.xml
<CustomObject>
    <description>Controls execution of all triggers</description>
    <label>Trigger Control</label>
    <pluralLabel>Trigger Controls</pluralLabel>
</CustomObject>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Which Apex class this service call resides in.</description>
    <inlineHelpText>Which Apex class this service call resides in.</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/DML_Operation__c.field-meta.xml
<CustomField>
    <fullName>DML_Operation__c</fullName>
    <description>Which trigger operation type to listen for.</description>
    <inlineHelpText>Which trigger operation type to listen for.</inlineHelpText>
    <label>DML Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE_INSERT</fullName>
                <default>true</default>
                <label>BEFORE_INSERT</label>
            </value>
            <value>
                <fullName>BEFORE_UPDATE</fullName>
            </value>
            <value>
                <fullName>BEFORE_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_INSERT</fullName>
            </value>
            <value>
                <fullName>AFTER_UPDATE</fullName>
            </value>
            <value>
                <fullName>AFTER_DELETE</fullName>
            </value>
            <value>
                <fullName>AFTER_UNDELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if this service call should execute.</description>
    <inlineHelpText>Determines if this service call should execute.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>The name of your method that begins the service call.</description>
    <inlineHelpText>The name of your method that begins the service call.</inlineHelpText>
    <label>Method Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/Order_of_Execution__c.field-meta.xml
<CustomField>
    <fullName>Order_of_Execution__c</fullName>
    <description>Controls the order in which your service calls are executed. Recommended working with 100, 200... To allow for maximum flexibility.</description>
    <inlineHelpText>Controls the order in which your service calls are executed. Recommended working with 100, 200... To allow for maximum flexibility.</inlineHelpText>
    <label>Order of Execution</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/meta-trigger/default/objects/Trigger_Control__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>Which SObject this service call is for.</description>
    <inlineHelpText>Which SObject this service call is for.</inlineHelpText>
    <label>SObject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/meta-trigger/default/classes/MetaTriggerSelector.cls
/**
 * Created by henryzhao on 2020-01-17.
 */

public without sharing class MetaTriggerSelector {

    public static List<Trigger_Control__mdt> retrieveTriggerControls(SObjectType obj, TriggerOperation dmlOperation) {
        return [
                SELECT
                        Apex_Class__c,
                        DeveloperName,
                        DML_Operation__c,
                        Id,
                        Is_Active__c,
                        Label,
                        Language,
                        MasterLabel,
                        Method_Name__c,
                        NamespacePrefix,
                        Order_of_Execution__c,
                        QualifiedApiName,
                        SObject__c
                FROM Trigger_Control__mdt
                WHERE Is_Active__c = TRUE AND
                SObject__c = :obj.getDescribe().getName() AND
                DML_Operation__c = :String.valueOf(dmlOperation)
                ORDER BY Order_of_Execution__c ASC
        ];
    }
}